### ISSUE TITLE
check.equal IndexError "list index out of range"

### ISSUE THREAD

**Issue by amit-selector** [okken/pytest-check#111]
Catching exception and printing traceback for this piece of code erroring:

```
            if not check.equal(response.status_code, 200, \
                        f"response status code expected 200 got {response.status_code}"):

```
Using pytest-check version 1.0.10

```
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 90, in wrapper
    func(*args, **kwds)
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 103, in equal
    assert a == b, msg
AssertionError: response status code expected 200 got 400
assert 400 == 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<snip>", line 231, in <snip>
    if not check.equal(response.status_code, 200, \
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 95, in wrapper
    log_failure(e)
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 342, in log_failure
    pseudo_trace_str = _build_pseudo_trace_str()
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 326, in _build_pseudo_trace_str
    (file, line, func, context) = get_full_context(level)
  File "/venv/lib/python3.10/site-packages/pytest_check/check_methods.py", line 298, in get_full_context
    (_, filename, line, funcname, contextlist) = inspect.stack()[level][0:5]
IndexError: list index out of range
```

**Comment by okken** [comment]
feel free to reopen if it's still a problem on current versions
